package com.navibees.core.model.license;

public enum NaviBeesFeature {
    Reserved_0,
    _2D_Maps,
    _3D_Maps,
    Reserved_3,
    Positioning,
    Reserved_5,
    Multi_Floor_Navigation,
    TurnByTurn_Navigation,
    Navigation_TTS,
    User_Based_Navigation,
    Reserved_10,
    Reserved_11,
    Location_Based_Notifications,
    Broadcast_Notifications,
    Profile_Based_Notification,
    Temporal_Based_Event_Activities_Notification,
    App_Analytics,
    Demographics_Analytics,
    Live_Location_Based_Analytics,
    Historical_Location_Based_Analytics,
    Analytics_Against_KPIs,
    Reserved_21,
    Reserved_22,
    Reserved_23,
    Reserved_24,
    Reserved_25,
    Reserved_26,
    Reserved_27,
    Reserved_28,
    Reserved_29,
    Reserved_30,
    Reserved_31
}
